### ISSUE TITLE
Comments & Wildcard Match

### ISSUE THREAD

**Issue by JeffHoremans** [hblumberg/elm-latex#1]
Hi, some things I found to be missing are the following:

__Single line comments.__
I added the following to detect them:
```
morecomment=[l]{--}
```
__Wildcard match.__
Resulted in errors (I think with testChar, but not sure), I formatted it as a symbol to resolve them like this:
```
{_}{{\_}}1
```

**Comment by hblumberg** [comment]
Thanks so much! Would you like to create a pull request or would you prefer that I push an update?

**Comment by JeffHoremans** [comment]
No problem, I added a pull request. 
And thank you! This package was exactly what I needed.
